baseURL = "https://jakobjankamminga.com"
title = "Kamminga, J.J."
author = "Jakob Jan Kamminga"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"
enableRobotsTXT = true

summaryLength = 30


[taxonomies]
  series = "series"
  tag = "tags"

[params]
    author = "Jakob Jan Kamminga"
    weapon = "owl.svg"
    weaponalt = "owl-white.svg"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        My personal website and portfolio.
    """
    publicationYear = "2019"
    listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]
    
    #blog section
                    #don't use spaces here!
    featuredTag1 = "web-development"
    featuredTag2 = "music"
    featuredTag3 = "writing"
    featuredTag4 = "announcements"

[markup.goldmark.renderer] 
 unsafe= true

[permalinks]
    stories = "/stories/:filename"
    music = "/music/:filename"

[outputs]
    section = ["JSON", "HTML"]