baseURL = "http://example.org/"
languageCode = "en-uk"
title = "Jakob Jan Kamminga"
theme = "Osprey"
tags = ["portfolio", "web development", "blog"]
canonifyURLS = true

[Params]
# Social media links in footer
twitter = "JaJaKamminga"
linkedin = "JakobJanKamminga"
github = "JJ-Kamminga"

# Copyright and theme author credit in footer
  copyright = false
  credit = false

# Contact form
ajaxBasin = "https://usebasin.com/f/62af8931a2ba"


[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 3
[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 4