baseURL = "https://agitated-curran-41fd3b.netlify.com/"
title = "Kamminga, J.J."
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Jakob Jan Kamminga"
    weapon = "owl.svg"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Please write anything here.
        Profiles, backgrounds, favorite things etc.
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]